### ISSUE TITLE
Error: Cannot find module '../../node_modules/raphael/raphael'

### ISSUE THREAD

**Issue by henrikakselsen** [dodo/node-raphael#5]
Following the instructions and using the demo files, but only get this error message

Error: Cannot find module '../../node_modules/raphael/raphael'
    at Function.Module._resolveFilename (module.js:338:15)
(...)

**Comment by notatestuser** [comment]
You're just backing up once, of course; so the path should look like the following:

```
../node_modules/raphael/raphael
```

However, that version of Raphael is pretty outdated and instead I'd recommend using my fork, which comes with Raphael 2.1.0 bundled and has been pretty rigorously tried and tested.

https://github.com/notatestuser/node-raphael/tree/quick-upgrade-2.1.0-compiled

I plan to update it to use an updated version of Raphael in the form of an NPM node module rather than have the code pushed to the repository, but it's ideal for most uses.

**Comment by dodo** [comment]
using current rapheal version now.
